<?php

$title = 'Edit Profile';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php	$form->setAttribute('action', $this->url('application/default', array('controller' => 'profile', 'action' => 'edit', 'id' => $profile->getId())));
	$form->setAttribute('class', 'form-horizontal');
	
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
// echo $this->formRow($client->getClient()->getName());

?>

<table class="table"> 
	
	<tr>
			<td>First Name</td>
			<td><?php echo $this->formRow($form->get('firstname')); ?></td>
	</tr>

	<tr>
			<td>Middle Name</td>
			<td><?php echo $this->formRow($form->get('middlename')); ?></td>
	</tr>

	<tr>
			<td>Last Name</td>
			<td><?php echo $this->formRow($form->get('lastname')); ?></td>
	</tr>
	<tr>
			<td>Address Line 1</td>
			<td><?php echo $this->formRow($form->get('address1')); ?></td>
	</tr>

	<tr>
			<td>Address Line 2</td>
			<td><?php echo $this->formRow($form->get('address2')); ?></td>
	</tr>
	
	<tr>
			<td></td>
			<td>
				<?php echo $this->formSubmit($form->get('submit')); ?>
				<span class="btn btn-primary"  onclick="javascript:history.back()" >Cancel</span>
			</td>
	</tr>
</table>

<?php
//echo $this->formRow($form->get('profiletype'));
//echo $this->formRow($form->get('notes'));
//echo $this->formRow($form->get('bankaccountname'));

//echo $this->formRow($form->get('bankaccountnumber'));


//echo $this->formRow($form->get('skills'));

//echo $this->formRow($form->get('nationalities'));
//echo $this->formRow($form->get('qualifications'));
//echo $this->formRow($form->get('jobtitles'));
//echo $this->formRow($form->get('industries'));
//echo $this->formRow($form->get('languages'));


echo $this->form()->closeTag();

$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.css'));
$this->headScript()->appendFile($this->basePath('js/chosen.jquery.min.js'));
/*	
*/

?>

<script type="text/javascript">
$(".chosen").chosen()
</script>