<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php


        if(isset($this->previous)):
            $class = '';
            $url   = $this->url($this->route, array('controller' => $this->mycontroller, 'page' => $this->previous));
        else:
            $class = 'disabled';
            $url = '#';
        endif;
        ?>

        </li><li class="<?=$class?>"><a href="<?=$this->url($this->route, array('controller' => $this->mycontroller, 'page' => $this->first));?>"><span class="fa fa-backward"></a></li>
        </li><li class="<?=$class?>"><a href="<?=$url;?>"><span class="fa fa-step-backward"></a></li>

        <?php foreach($this->pagesInRange as $page):?>
            <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?=$this->url($this->route, array('controller' => $this->mycontroller, 'page' => $page))?>"><i class="icon"><?=$page;?></i></a>
        <?php endforeach;?>

        <?php
        if(isset($this->next)):
            $class = '';
            $url   = $this->url($this->route, array('controller' => $this->mycontroller, 'page' => $this->next));
        else:
            $class = 'disabled';
            $url = '#';
        endif;
        ?>
        </li><li><a href="<?=$url;?>"><span class="fa fa-step-forward"></span></a></li>
        </li><li><a href="<?=$this->url($this->route, array('controller' => $this->mycontroller, 'page' => $this->last));?>"><span class="fa fa-forward"></a></li>
    </ul>
<?php endif; ?>
